import styled from "@emotion/styled";

export const Wrapper = styled.div`
  box-sizing: border-box;
  width: 1200px;
  margin: 60px auto 20px auto;
  padding: 80px;
  box-shadow: 0px 4px 20px rgba(0, 0, 0, 0.2);
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;
export const Header = styled.div`
  width: 996px;
  height: 90px;
  border-bottom: 1px solid #bdbdbd;
  padding: 10px;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 30px;
`;
export const Profile = styled.div`
  width: 500px;
  padding: 5px;
  height: 30px;
  display: flex;
  flex-direction: row;
  justify-content: space-around;
  align-items: center;
`;
export const ProfilePhoto = styled.div``;
export const ProfileWrapper = styled.div``;
export const ProfileName = styled.div``;
export const ProfileDate = styled.div``;
export const IconWrapper = styled.div``;
export const Icon = styled.div``;
export const IconLink = styled.div``;
export const IconMap = styled.div``;
export const Middle = styled.div``;
export const Product = styled.div``;
export const Remarks = styled.div``;
export const Name = styled.div``;
export const Price = styled.div``;
export const Like = styled.div``;
export const LikeIcon = styled.div``;
export const LikeNum = styled.div``;
export const Carousel = styled.div``;
export const Contents = styled.div``;
export const Tag = styled.div``;
export const Map = styled.div``;
export const Footer = styled.div``;
export const ListBtn = styled.button``;
export const BuyBtn = styled.button``;
